"""Add username to User model

Revision ID: 557616779bd3
Revises: 
Create Date: 2024-12-12 00:48:10.300140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557616779bd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_email_key', ['username'])

    # ### end Alembic commands ###
